import React from 'react';
import type { Metadata } from 'next';
import Providers from './providers';
import { Layout } from '@/layout';

export const metadata: Metadata = {
  title: 'OnCharge',
  description: 'Generated by create next app'
};

interface RootLayoutProps {
  children: React.ReactNode
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => (
  <html lang="en">
    <body>
      <Providers>
        <Layout>
          {children}
        </Layout>
      </Providers>
    </body>
  </html>
);

export default RootLayout;
